### ISSUE TITLE
User: register

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#1]
## Value statement: 
As a **user** 
I need to be able to **create an account** 
to **save my personal filters** for the map.

## Description (Text, Scribble, Wireframe, Design)
<img width="540" alt="Bildschirmfoto 2020-12-21 um 20 29 42" src="https://user-images.githubusercontent.com/68876538/102814709-5a757000-43cb-11eb-8cde-78e2e9b16ec6.png">

## Acceptance criteria
- [x] The register form has 4 input fields, first name, last name, email and password – and a submit button to create a new user
- [x] The register form also has a link to the login page for already registered users

## Tasks
- [x] Register form component
- [x] Register component
- [x] Custom Request for POST user
- [x] Change response from user data to token 

## Size
medium
