### ISSUE TITLE
Tag Entity with custom Serializer

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#10]
## Value statement 
As a **user** 
I need **to be able to see tags related to the place** I am looking for
and to **add tags** to this place 
so that in the future **I can filter places by tags**
## Acceptance criteria
- [x] The user can write her/his own tags and save them
- [x] The user can check if there are any tags in the database
## Tasks
- [x] Make a feature branch
- [x] Tag Entity with one attribute: name
- [x] Custom serializer with toArray function plus serialize and deserialize function
- [x] POST controller with name
- [x] GET controller with ORM id plus name
## Size
small
