### ISSUE TITLE
Many to Many Relation: Tag Place

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#13]
## Value statement - a requirement, not a solution
As a **user** 
I need **to save tags related to a certain place** 
so that I can later **filter places by my custom tags** 

## Acceptance criteria
- [x] Saving a tag for a new place also saves this place
- [x] Saving a tag for a saved place relates it to this specific place
- [x] Duplicates are not possible (as long as they are written identical) – neither for tag nor place
- [x] Multiple tags for one place are possible
- [x] Relating the same tag to multiple places is possible 

## Tasks
- [x] Many to Many relation for tag and place
- [x] Find existing tag or save new tag
- [x] Find existing place or save new place
- [x] Relate tag to place

## Size
medium
