### ISSUE TITLE
POST controller tags (return related places)

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#14]
## Value statement
As a **user** 
I need to find **saved tags and their related place(s)** 
so that I can in the next step see a **map with marked places filtered by my tag(s)** 

## Acceptance criteria
- [x]  Clear response when tag, sent by the user, does not exist in database
- [x] If tag does exist, POST returns all related places with their attributes

## Tasks
- [x] Find posted tag and the places it points to 
- [x] Return an empty array if tag does not exist
- [x] Return all related places with attributes

## Size
small
