### ISSUE TITLE
POST controller places (return related tags)

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#15]
## Value statement
As a **user** 
I need to find **tags related to a saved place** 
so that I know which **tags to add or delete** 

## Acceptance criteria
- [x] Clear response when place sent does not exist in database
- [x] If place exists response are all related tags 

## Tasks
- [x] Find posted place and it's tags in the database
- [x] Return an empty array if place does not exist
- [x] Return all related tags with their id 

## Size
small
