### ISSUE TITLE
Place Info Page

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#16]
## Value statement 
As a **user** 
I need to **see name, address and tags a place** 
so that I can **find my way to it or work on my tags for it** 

## Description (Text, Scribble, Wireframe, Design)
![MapIt_Info_Page](https://user-images.githubusercontent.com/68876538/100611329-78423e80-3311-11eb-8931-f69a614ba751.jpg)

## Acceptance criteria
- [x] Name and address are shown seperate from the tags

## Tasks
- [x] Insert name and address at the top
- [x] Insert tags under it with a bit of space
- [x] At the bottom insert a yet non-functional input field for adding tags 

## Size
small
