### ISSUE TITLE
Place Info Page: option to add tags

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#17]
## Value statement 
As a **user** 
I need to see **a place and its tags separately** 
to **edit the tags**  

## Description (Text, Scribble, Wireframe, Design)
![MapIt_Info_Page_add_tag](https://user-images.githubusercontent.com/68876538/100611437-9f990b80-3311-11eb-8b22-cbd0f4238d05.jpg)

## Acceptance criteria
- [x] Clicking a marker opens a separate page for the specific place
- [x] Tags can be added by typing in the input field and pressing Enter
- [x] Added Tags are shown on the page and it's possible to add more

## Tasks
- [x] useState for input value
- [x] state "currentPlace" from App component as part of the object that is going into POST
- [x] onUpdateTags function creates this object with input value as tag's name
- [x] POST for the add controller
- [x] fetch updates addedTags of state in PlaceDetailPage component

## Size
middle
