### ISSUE TITLE
Marker on the Map

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#18]
## Value statement - a requirement, not a solution
As a **user** 
I need **markers on my map** 
to see **my distance to a place and to filter more/less places** 

## Acceptance criteria
- [ ] Marker pops up when filtered by place
- [ ] Marker pops up when filtered by tag(s)

## Tasks
- [ ] useState for Marker(s)
- [ ] Mark a place when user picked it in the place search bar
- [ ] Mark place(s) when user entered a tag in the tag search bar

## Size
medium
