### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#2]
## Value statement: 
As a **user** I need to be able to **log into my account**
so that I can **access my saved filters** for the map.

## Description (Text, Scribble, Wireframe, Design)

<img width="483" alt="Login_page" src="https://user-images.githubusercontent.com/68876538/99785771-e4f15800-2b1d-11eb-9751-d337c2694994.png">

## Acceptance criteria
- [x] The login form has 2 input fields, email and password, and a submit button to log in
- [x] The login form also has a link back to the register page for users who do not have an account yet and need to create one first

## Tasks
- [x] Login form component with useState for userProfile (email, password)
- [x] Login component with headline and login form component

## Size
small
