### ISSUE TITLE
Delete Tag-Place Relation

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#24]
## Value statement 
As a **user** 
I need **to delete tags** related to a place 
to ** update my custom filter mechanism** 

## Acceptance criteria
- [x] Deleting a tag removes the relation between the chosen tag and place
- [x] Deleting a tag does not remove it entirely, if it is connected to other places
- [x] If the tag is just connected to this one place, the tag will be deleted
- [x] The place will not be deleted, if it has other tags 
- [x] If the place only has this one tag, the place will be deleted

## Tasks
- [x] Check if tag exists in the database – if not, throw an error
- [x] Check if place exists in the database – if not, throw an error
- [x] Check if tag and place are in fact related – if not, throw an error
- [x] Check number of this tag's related places 
- [x] Check number of this place's related tags
- [x] Remove the relation between them 
- [x] Delete tag and place, if both have just 1 relation
- [x] Delete tag, if it has just 1 relation
- [x] Delete place, if it has just 1 relation 
- [x] If both have more than 1 relation, save changes to the database 

## Size
medium
