### ISSUE TITLE
Business Logic (find, delete)

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#26]
## Value statement
As a **developer** 
I need to **outsource logic from find methods and delete method** 
for a **cleaner, more maintainable code base** 

## Acceptance criteria
- [x] TagController imports find logic for the tags
- [x] TagController imports find logic for the related places
- [x] PlaceController imports find logic for the related tags

## Tasks
- [x] Create a services directory
- [x] Outsource the find and sort logic in TagController for related places by name into its own class
- [x] Outsource the find and sort logic in TagController for related places by id into its own class
- [x] Outsource the find and sort logic in PlaceController for related tags into its own class
- [x] Import the classes to find and sort places in TagController
- [x] Import the class to find and sort tags in PlaceController

## Size
small
