### ISSUE TITLE
Cypress

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#27]
## Value statement - a requirement, not a solution
As a **developer** 
I need **a solid understanding of Cypress basics** 
to **write e2e tests** 

## Acceptance criteria
- [x] Installed Cypress version runs stable
- [x] Failing and passing tests are displayed correctly 

## Tasks
- [x] Install Cypress
- [x] Initial test – passing, failing
- [x] Test page visit
- [x] Test query for an element
- [x] Test clicking an element
- [x] Test making an assertion
- [x] Look at debugging
- [x] Look time travel
- [x] Look at snapshots
- [x] Look at error messages
- [x] Look at console output
- [x] Look at special commands
- [x] Set up IntelliSense with jsconfig.json
- [x] Set up intelligent code completion with tsconfig.json

## Size
medium
