### ISSUE TITLE
Main view

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#3]
## Value statement 
As a **user** 
I need to **move and zoom in and out of the map** 
so that I can **find my way** to the place I am looking for.
 
## Description (Text, Scribble, Wireframe, Design)

<img width="491" alt="Main_page_view--raw_map" src="https://user-images.githubusercontent.com/68876538/99784991-dfdfd900-2b1c-11eb-8c8c-90c11fc3c2ed.png">

## Acceptance criteria
- [x] Dragging moves the map 
- [x] Spreading zooms in on it
- [x] Pinching zooms out of it 

## Tasks
- [x] Create a feature branch
- [x] Install leaflet (npm package)
- [x] Install react-leaflet (npm package)
- [x] Add link in index.html to import leaflet
- [x] Use app.css and a leaflet CSS class for initial setup
- [x] Create a Map component
- [x] Fetch OpenStreetMap API

## Size
medium
