### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#36]
## Value statement 
As a **user** 
I need **a navigation bar** 
to **switch to a list with all places, use the tag search and log out** 

## Acceptance criteria
- [x] Symbol for places list, input field and symbol for logout are at the bottom of the screen
- [x] Clicking on place symbol shows a list of all tagged places
- [x] Clicking on logout symbol brings you to main route for now
- [x] Text can be entered in input field and disappears by pressing enter 

## Tasks
- [x] Navigation bar at bottom of viewport with navigation list and list items
- [x] React Router's Link component to load places list and handle logout
- [x] Search tag component set in the middle between links to the two pages
- [x] Component as info page for all places
- [x] Places list component
- [x] Places list item component
- [x] Component for logout

## Size
large
