### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#39]
## Value statement - a requirement, not a solution
As a **developer** 
I need **a landing page** 
to give the app **time to load** in the background 

## Acceptance criteria
- [x] The landing page opens first
- [x] The app just starts without action from the user
- [x] The design is coherent with the rest of the app

## Tasks
- [x] Center big logo in the middle, app name under it
- [x] Put component in the root directory
- [x] For now, let a setTimeout() link to the main page

## Size
small
