### ISSUE TITLE
Technical Setup FE + BE

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#4]
## Value statement
As a **developer** 
I need an **initial setup for frontend and backend** 
to be able to **check the connection between them** 

## Acceptance criteria
- [x] Functional frontend
- [x] Functional backend
- [x] Working connection between frontend and backend

## Tasks
- [x] Initial React setup
- [x] Initial Symfony setup
- [x] Create a User entity with attributes: name, email, password
- [x] GET controller for User
- [x] POST controller for User
- [x] Fetch user in frontend and display it (console log)
- [x] Post user data in frontend and display the response (console log) 

## Size
medium

**Comment by lennart-sakowsky** [comment]
## Value statement
As a **developer** 
I need **an initial setup**
to test the **connection between FE and BE** 

## Description (Text, Scribble, Wireframe, Design)

## Acceptance criteria
- [x] The POST controller creates a new entry in the table and returns it as JSON
- [x] The GET controller finds all entries in the table and returns them as JSON

## Tasks
- [x] Basic setup in React and Symfony
- [x] 1st database entity
- [x] POST controller for entity
- [x] GET controller for entity
- [x] Fetch in React and show in frontend  

## Size
small
