### ISSUE TITLE
ManyToOne: tag endpoints

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#40]
## Value statement - a requirement, not a solution
As a **user** 
I need **to get tag related places and delete tags** 
so that **I can filter the map and edit saved places** 

## Acceptance criteria
- [x] Making a PUT for a tag gives back all related places
- [x] If requested tag does not exist, response is an error message
- [x] Making a DELETE for a tag removes it from the database (and the related place if it has no other relations)
- [x] If requested tag does not exist, response is an error message
- [x] If requested place does not exist, response is an error message
- [x] If tag (or place) or the relation could not be deleted, response is an error message
- [x] If relation (and tag or place) are removed, response is a success message

## Tasks
- [x] TagController PUT: add user validation, get requested tag – if not found, send error response
- [x] TagController PUT: get related places – response them
- [x] TagController DELETE: add user validation, get requested tag – if not found, send error response
- [x] TagController DELETE: get requested place – if not found, send error response
- [x] TagController DELETE: remove tag place relation and delete tag and/or place if they have no other relations

## Size
medium
