### ISSUE TITLE
Design: Navigation, Map, Header

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#42]
## Value statement
As a **user** 
I need a **balanced design** of navigation bar, map and header
to quickly **find my way in the app and on the map** 

## Acceptance criteria
- [x] The map's overall design is not too colorful or detailed
- [x] The navigation bar has a clear symbol for the page showing all tagged places, a well proportioned input field, a clear and coherent logout symbol

## Tasks
- [x] Create SVG of the app's logo in red color
- [x] Find and implement unordered list SVG for places page
- [x] Find and implement logout SVG
- [x] Set global color and global font
- [x] Header with app name and logo

## Size
medium
