### ISSUE TITLE
Refactoring: structure, services, forms

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#45]
## Value statement 
As a **developer** 
I need **a cleaner structure and more reusable components** 
to have a **more understandable, easier maintainable code** 

## Acceptance criteria
- [x] Every file affected by the new structure has to be put to the test, one by one
- [x] The hook to fetch data has to be put to the test in every scenario

## Tasks
- [x] Directory services: delete now redundant services 
- [x] New directory common: CustomMap, Navigation, Header, Logo, PlaceSearch
- [x] New directory input: new FormInput as template, AddTagInput, SearchTagInput
- [x] New directory hooks: useFetch
- [x] New directory place: PlaceDetailPage, PlaceInfo, AddedTagList
- [x] New directory allPlaces: AllPlacesPage
- [x] New directory landing: LandingPage
- [x] New directory login: Login, LoginForm
- [x] Backend: Move parts of the DELETE controller in Services directory 

## Size
large
