### ISSUE TITLE
Testing with Jest

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#46]
## Value statement
As a **developer** 
I need **well tested code** 
for **more stable, easier maintainable** software 

## Acceptance criteria
- [x] All reducers and services have to be testet

## Tasks
- [x] Test postingReducer
- [x] Test placeReducer
- [x] Test deleteReducer
- [x] Test filterReducer
- [x] Test useCombinedReducer
- [x] Test registerUser (services)
- [x] Test loginUser (services)
- [x] Test deleteUser (services)
- [x] Test getPlaces (services)
- [x] Test postTag (services)
- [x] Test deleteTag (services)

## Size
large
