### ISSUE TITLE
User Entity: One to Many Token

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#49]
## Value statement - a requirement, not a solution
As a **user** 
I need **a token/bearer** 
to **safely log into my account** 

## Acceptance criteria
- [x] User can register
- [x] User can log in and gets a token, valid for 30 min
- [x] User can log out
- [x] Old tokens get deleted when logging out or logging in

## Tasks
- [x] Set up ORM for User and Token Entity
- [x] TokenRepository: create token, valid for 30 min, set timezone to Berlin
- [x] TokenRepository: delete token
- [x] TokenSerializer: serialize value, validUntil, user id
- [x] AuthenticationService: bearer token in header?, token in repo?, only return user if token is valid
- [x] AuthenticationService: delete any token that is not valid anymore
- [x] AuthenticationController: login endpoint with POST, user in repo?, delete old token(s), create a new token, serialize it
- [x] AuthenticationController: logout endpoint with DELETE, received token exists in repo?, token still valid?, delete invalid/valid token
- [x] UserController: endpoint with GET, response with all users if received token is valid
- [x] UserController: endpoint with POST, register new user if mail does not exist yet

## Size
large
