### ISSUE TITLE
User Entity: Password Hashing

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#50]
## Value statement - a requirement, not a solution
As a **developer** 
I need to **encrypt users' passwords** 
to **protect their privacy/accounts**

## Acceptance criteria
- [ ] User password is encoded and validated safely

## Tasks
- [ ] Use Symfony's password encoder interface
- [ ] LoginService: find user – if it fails, user is not valid
- [ ] LoginService: use encoder to validate password, save this data, return it with user
- [ ] AuthenticationController: add LoginService to validate user

## Size
medium
