### ISSUE TITLE
ManyToOne: Tag and Place to User

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#51]
## Value statement - a requirement, not a solution
As a **user** 
I need **to save tags and places under my account** 
to **open the place detail page and tag the chosen place** 

## Acceptance criteria
- [x] Tags are related to user
- [x] Places are related to user
- [x] Making a POST for a searched place gives back just the place if user has not saved a tag for it yet
- [x] Making a POST for a searched place gives back the place and user tags if user has saved it before
- [x] Making a GET gives back all places with their tags saved by the user
- [x] Making a POST with tag and place saves tag (and place) in relation to place and user in the database

## Tasks
- [x] ManyToOne for tag and user
- [x] ManyToOne for place and user
- [x] PlaceController POST: add user validation, get related places – if empty, send response 
- [x] PlaceController POST: find requested place in related places – if null, send response with post data, if found, send response with data saved for this place
- [x] PlaceController GET: add user validation, get related places – send response with saved data
- [x] TagController POST: add user validation, get related tags – if requested tag not in database, create it, relate to user
- [x] TagController POST: get related places – if requested place not in database, create it, relate to user, relate to tag, flush and send response

## Size
medium
