### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#56]
## Value statement
As a **developer** 
I need **clear services** 
to keep my **controllers tidy and easily maintainable**

## Acceptance criteria
- [x] No business logic in TagController
- [x] No business logic in PlaceController
- [x] Clear naming, nothing unused remains

## Tasks
- [x] PlaceController: delete POST
- [x] UserController: delete GET
- [x] TagController: delete PUT
- [x] TagController: move business logic in POST to service
- [x] TagController: move business logic in DELETE to service
- [x] Delete unused services
- [x] Rename unclear services

## Size
medium
