### ISSUE TITLE
User: login / logout

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#57]
## Value statement: 
As a **user** 
I need to be able to **log into my account** 
to **save my personal filters** for the map.

## Acceptance criteria
- [x] Display loading message
- [x] A successful login opens the main page
- [x] Unsuccessful login displays an error message 

## Tasks
- [x] lib folder with function to save to and load from localStorage
- [x] POST with e-mail and password, save token from response in localStorage
- [x] App.js: Save token in state
- [x] authHeader.js for headers with and without bearer token
- [x] Implement authHeader in useFetch hook, make every request work
- [x] DELETE with loaded token in header
- [x] useState for loading, logged in, error

## Size
medium
