### ISSUE TITLE
Search Bar for Places

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#6]
## Value statement
As a **user** 
I need **to search for places** 
so that I can subsequently **add tags to them** 
## Description (Text, Scribble, Wireframe, Design)

<img width="479" alt="Search_bar" src="https://user-images.githubusercontent.com/68876538/100118006-b359f300-2e75-11eb-832a-b7543f828dfa.png">

## Acceptance criteria
- [x] Clicking/tapping the input field gives it focus and the user can write in it
- [x] Typing text into the input field opens an overlay menu with place suggestions
- [x] Typing more text narrows down the suggestions
- [x] Tapping on a suggestion starts the query
- [x] A successful query drops a marker on the map

## Tasks
- [x] Create a feature branch
- [x] Create a search bar component
- [x] Fetch places with the ArcGIS API
- [x] Use Esri Leaflet Geocoder's search control 
- [x] Make a POST on the backend API with the result from the ArcGIS query
- [x] Save the related tags of the response (if there are any) in a state

## Size
medium
