### ISSUE TITLE
Global state

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#61]
## Value statement - a requirement, not a solution
As a **developer** 
I need a **global state with places and their tags** 
to **reduce server requests and access this data more easily**

## Acceptance criteria
- [x] The server's response holds two additional fields for a place entity: the booleans active and related 
- [x] This response is saved by a reducer and the action is provided globally
- [x] The state is changed when setting a place active (to add or delete tags), setting a place or places related (by searching for places with a specific tag) or setting it back to inactive/unrelated
- [x] Other requests are only made when adding or deleting a tag – or when user logs out

## Tasks
- [x] Add boolean fields active and related to place entity
- [x] Update serializers
- [x] Implement reducers in App.js
- [x] Implement hook to combine reducers' actions and states
- [x] Implement global dispatch in App.js 
- [x] AllPlacesPage works with this dispatch
- [x] PlaceSearch works with this dispatch
- [x] SearchTagInput works with this dispatch
- [x] PlaceDetailPage works with this dispatch 

## Size
large
