### ISSUE TITLE
Search Bar for Tags

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#8]
## Value statement
As a **user** 
I need **to search for tags** 
to see **related places marked on the map** 

## Acceptance criteria
- [x] Entering text in the input and pressing enter starts a query in the database
- [x] Higher or lower case does not affect the result
- [x] After the query is complete markers show up on the map
- [x] The markers disappear when visiting another page, searching a place or starting another search for tag related places

## Tasks
- [x] fetch getTaggedPlaces in services (PUT) sending tag name in body
- [x] onKeyDown function calls getTaggedPlaces and updates state in App component: taggedPlaces
- [x] Clicking on link for AllPlacesPage sets the state for taggedPlaces back to an empty object
- [x] Starting the fetch for place data in the esri component also sets the state back to an empty object 

## Size
medium
