### ISSUE TITLE
Place Entity with custom Serializer

### ISSUE THREAD

**Issue by lennart-sakowsky** [lennart-sakowsky/capstone-project#9]
## Value statement 
As a **user** 
I need to know if a **place already exists in the database** and I need to **save it (indirectly), if it doesn't**
so that I can (in the next step) **see related tags, edit them or create the first one**

## Acceptance criteria
- [x] It is possible to check, if the requested place exists in the database
- [x] A place can be saved in the database

## Tasks
- [x] Make a feature branch
- [x] Place Entity with attributes: name, street, zipcode, latitude, longitude
- [x] Custom serializer with toArray function plus serialize and deserialize function
- [x] POST controller with name, street, zipcode, latitude, longitude
- [x] GET controller with ORM id plus all attributes

## Size
small

**Comment by lennart-sakowsky** [comment]
## Value statement 
As a **user** 
I need to be able to **check if a place exists in the database** 
so that – at later stage – **I can either add the first tag or new, non-redundant tags** to it
## Description (Text, Scribble, Wireframe, Design)
## Acceptance criteria
- [x] The user looks for a specific place and gets a response if it exists in the database 
- [x] If the place is saved in the database, the response will be Doctrine's ORM id for this place 
## Tasks
- [x] Make a feature branch
- [x] Place Entity with these attributes: name,  address,  zipcode,  latitude,  longitude
- [x] Custom serializer with toArray function plus serialize and deserialize function
- [x] POST controller with name, address, zipcode, latitude, longitude
- [x] GET controller with ORM id plus name, address, zipcode, latitude, longitude for testing
## Size
medium
